SRE White paper - openshift cluster
bcgov/platform-services-sre pull request #12
Opened 2022-11-09 00:48 UTC by ShellyXueHan

2022-11-09 23:27 UTC, StevenBarre requested changes
Looks like this was copied from a word/google doc? Needs a lot of formatting works still. I would recommend using VSCode with a few Markdown addons to help clean it up.

- https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint
- https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one

You can also use the View File option in GitHub to see how its rendered.
![image](https://user-images.githubusercontent.com/24236108/200963771-42385e9b-32e1-4788-8d0d-9dedfc3c9b27.png)

The contents of the doc however look good to me overall, just a few nit picks.

2022-11-09 23:27 UTC, StevenBarre commented on docs/white-paper.md
> +**Current DXE Team SLO against the Cluster API Availability**
```suggestion
**Current DXC Team SLO against the Cluster API Availability**
```

2022-11-09 23:27 UTC, StevenBarre commented on docs/white-paper.md
> +The above is a high-level graphic of metrics to use for USE Method
What graphic?

2022-11-09 23:27 UTC, StevenBarre commented on docs/white-paper.md
> +max by (pod,namespace) (container_memory_working_set_bytes{container!=""} / on (pod,namespace,container)
This query doesn't look right?

We don't have swap on our clusters, so there should be no paging of memory. Once its full it gets OOM Killed.

2022-11-17 16:26 UTC, mitovskaol commented on docs/white-paper.md
> +•	KLab2 Cluster
```suggestion
•	KLab2 Cluster
•	CLab Cluster
```

2022-11-17 16:37 UTC, mitovskaol commented on docs/white-paper.md
> +•	KLab2 Cluster
```suggestion
•	KLab2 Cluster
•	CLab Cluster
```

2022-11-17 16:37 UTC, mitovskaol commented on docs/white-paper.md
> +•	99.5% availability for multi-node application deployments
```suggestion
•	99.95% availability for application deployments with a geographic failover
```

2023-11-07 00:22 UTC, StevenBarre commented on docs/white-paper.md
> +max by (pod,namespace) (container_memory_working_set_bytes{container!=""} / on (pod,namespace,container)
pagein / pageout are not necessarily related to swap, should be fine to leave in. https://serverfault.com/a/270324/27378

2023-11-07 00:55 UTC, w8896699 approved these changes
I have updated based on comment. Also I have create a ticket to do more research on cluster wide memory monitoring standard

2023-11-07 00:55 UTC, merged