added days function to the script
bcgov/platform-services-sre pull request #20
Opened 2023-08-25 21:13 UTC by rajpalc7

2023-08-28 16:17 UTC, ShellyXueHan requested changes
Thank you for the contribution! Please take a look at the comments :)

2023-08-28 16:17 UTC, ShellyXueHan commented on uptime/monitor-setup/uptime-rc-webhook.js
> + * Usage on uptime.com webhook integration setup: put this in the Custom HTTP Headers to tag ppl in the messagecontactusers: @<user1_rocketchat_account> @<user2_rocketchat_account> ... ,
please do not remove the backward quote, it's meant to be an example

2023-08-28 16:17 UTC, ShellyXueHan commented on uptime/monitor-setup/uptime-rc-webhook.js
> +/ globals console, _, s /
`/* */` is used for comments, does it still work without?

2023-08-28 16:17 UTC, ShellyXueHan commented on uptime/monitor-setup/uptime-rc-webhook.js
> +/ exported Script /
same here!

2023-08-28 16:17 UTC, ShellyXueHan commented on uptime/monitor-setup/uptime-rc-webhook.js
> +}
please add the empty line at the end of the file.

2023-08-28 16:17 UTC, ShellyXueHan commented on uptime/monitor-setup/uptime-rc-webhook.js
> -        alias: USERNAME,
Looks like you are switching it from spaces to tabs, it's generally better to use space so the indentation don't change in different places. Please revert back!

2023-08-30 14:22 UTC, WadeBarnes requested changes
You still have some whitespace issues to address @rajpalc7.

2023-08-31 12:11 UTC, WadeBarnes requested changes
That looks way better @rajpalc7.  Please squash and rebase the changes into a single commit on the latest code.  Thanks

2023-08-31 16:13 UTC, ShellyXueHan approved these changes
LGTM, thank you!

2023-08-31 16:13 UTC, ShellyXueHan commented on uptime/monitor-setup/uptime-rc-webhook.js
> +  const time = (totalSeconds) => {
```suggestion
const time = (totalSeconds) => {
```

2023-08-31 16:13 UTC, ShellyXueHan commented on uptime/monitor-setup/uptime-rc-webhook.js
> +  class Script {
```suggestion
class Script {
```

2023-08-31 16:13 UTC, ShellyXueHan commented on uptime/monitor-setup/uptime-rc-webhook.js
> +    process_incoming_request({ request }) {
```suggestion
  process_incoming_request({ request }) {
```

2023-08-31 16:13 UTC, ShellyXueHan commented on uptime/monitor-setup/uptime-rc-webhook.js
> +     statusText = `UP`;
```suggestion
      attachmentColor = `#36A64F`;
      statusText = `UP`;
```

2023-08-31 16:15 UTC, WadeBarnes approved these changes

2023-08-31 20:52 UTC, merged