update uptime.com RC notification scripts and sample
bcgov/platform-services-sre pull request #28
Opened 2023-11-16 23:07 UTC by ShellyXueHan

2023-11-17 14:23 UTC, WadeBarnes requested changes
Looking good.  Just a couple of comments.

2023-11-17 14:23 UTC, WadeBarnes commented on uptime/monitor-setup/uptime-rc-webhook-2023-11-16.js
> +      titleLink = 'https://uptime.com';
`titleLink` is not being used.

2023-11-17 14:23 UTC, WadeBarnes commented on uptime/monitor-setup/uptime-rc-webhook-2023-11-16.js
> +      attachmentText += 'Back to normal now!';
Missing an indication of how long the monitored service was down for; see previous RC script.

2023-11-20 21:45 UTC, WadeBarnes approved these changes
LGTM

2024-04-29 17:40 UTC, w8896699 approved these changes
Looks good to me

2024-04-29 17:44 UTC, merged